question_data = [
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Bulls are attracted to the color red.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Ananas is mostly used as the word for Pineapple in other languages.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Pluto is a planet.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The Lego Group was founded in 1932.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "'27 Club' is a term used to refer to a list of famous actors, musicians, and artists "
                     "who died at the age of 27.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside "
                     "swimming pools and drinking water.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Vietnam's national flag is a red star in front of a yellow background.",
         "correct_answer": "False", "incorrect_answers": ["True"]}
]
